name: Generate Snake

on:
  schedule: # Run every 24 hours
    - cron: "0 0 * * *"
  workflow_dispatch: # Allow manual runs

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: metinmeki
          outputs: dist/snake.svg

      - name: Push snake to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
